name: Chatter
main: com.dral.Chatter.Chatter
version: 2.2.0
author: Dral
website: http://twitter.com/dralletje
commands:
    reloadchatter:
        description: reloads chatter :P
        usage: /reloadchatter
    chatter:
        description: just nothing :P
        usage: /chatter
softdepend: [CraftIRC]