name: Chatter
main: com.dral.Chatter.Chatter
version: 2.2.0
authors: [Dral, Tatara88]
website: http://twitter.com/dralletje
commands:
    reloadchatter:
        description: reloads chatter :P
        usage: /reloadchatter
    chatter:
        description: just nothing :P
        usage: /chatter
permissions:
  chatter.reload:
    description: Allows you to use the '/reloadchatter' command.
  chatter.colors:
    description: Allows people to use colors in chat.
  chatter.k:
    description: Only give this to cool people, cuze this will freeze everyone!
softdepend: [CraftIRC]